### ISSUE TITLE
fix(python-sdk): workspace list model drift (agentNeedsRefresh) + s_ws_crud scenario drift (create-empty-runtime)

### ISSUE THREAD

**Issue by lenaxia** [lenaxia/LLMSafeSpaces#867]
## Context

Unmasked by #861's Python canary bootstrap fix (the section had never executed in CI before — earlier Go failures aborted the job). The first real run surfaced two NEW pre-existing drifts in `s_ws_crud` (scenario 7 of 22), beyond the 10 failures already fixed in #861.

## Findings (run 31874561400, job 94995297847)

1. **Python SDK model drift** — `FAIL list: WorkspaceListItem.__init__() got an unexpected keyword argument 'agentNeedsRefresh'`. The API's workspace list response now includes `agentNeedsRefresh`, but `sdks/python/llmsafespaces`'s `WorkspaceListItem` dataclass doesn't accept it. Go/TS SDKs presumably handle it (their canaries pass) — the Python SDK was never updated.
2. **Scenario drift** — `FAIL create-empty-runtime: expected an error but got none`. The scenario expects the API to reject an empty runtime; the product now intentionally resolves empty runtimes to the default image (default-image tier hierarchy, see #809/#856 direction). The scenario's expectation is stale.

## Fix direction

1. Add `agentNeedsRefresh` (bool, optional) to the Python SDK's `WorkspaceListItem` + any other workspace models carrying it; add a model round-trip test.
2. Update `s_ws_crud`'s `create-empty-runtime` check to assert the new behavior (accepts + resolves to default) or repurpose it to assert the resolved image matches the configured default.
3. Re-run the full Python canary section — more drift may surface past scenario 7 (the section has still never completed a full green run; scenarios 8-22 remain unproven in CI).

Note: the SDK Integration canary job is `continue-on-error: true` by design until it passes consistently (`ci.yml` TODO: flip to false).
